require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  pod 'react-native-video', :path => '../node_modules/react-native-video', :modular_headers => true

  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas', :modular_headers => true

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons', :modular_headers => true

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation', :modular_headers => true

  pod 'OpenSSL-Universal', :modular_headers => true

  pod 'GoogleUtilities', :modular_headers => true

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!

  post_install do |installer|
    react_native_post_install(installer)
  end
end
